"""new

Revision ID: 94121677a2e2
Revises: 890d03491bc3
Create Date: 2025-05-28 10:08:47.562528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94121677a2e2'
down_revision: Union[str, None] = '890d03491bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EQ_COMPRESSOR_UNIT', sa.Column('diam', sa.Float(), nullable=True, comment='Диаметр'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EQ_COMPRESSOR_UNIT', 'diam')
    # ### end Alembic commands ###
